services:
  postgres:
    image: postgres:17

  rabbitmq:
    image: rabbitmq:4-management

  redis:
    image: redis:7-alpine

  minio:
    image: bitnamilegacy/minio:2025.7.23-debian-12-r5

  identity.api:
    image: ${DOCKER_REGISTRY-}identityapi
    build:
      context: .
      dockerfile: Services/Identity/Identity.Api/Dockerfile

  parishcoordination.api:
    image: ${DOCKER_REGISTRY-}parishcoordinationapi
    build:
      context: .
      dockerfile: Services/ParishCoordination/ParishCoordination.Api/Dockerfile

  yarpapigateway:
    image: ${DOCKER_REGISTRY-}yarpapigateway
    build:
      context: .
      dockerfile: ApiGateway/YarpApiGateway/Dockerfile

volumes:
  postgres_data:
  minio_data:
